class_name NCONSTANTS2

enum {  CFI_TIMESTAMP 		= -1, 
		CFI_TIMESTAMPPREV 	= -2,
		
		CFI_PLAYER_NODENAME	= -3,
		CFI_TIMESTAMP_F0 	= -4,
		CFI_TIMESTAMP_RECIEVED = -5, 
		CFI_ZERO = 0,
		
		CFI_VRORIGIN_POSITION = 50,
		CFI_VRORIGIN_ROTATION = 51,
		CFI_VRHEAD_POSITION = 60,
		CFI_VRHEAD_ROTATION = 61,
		
		CFI_VRHANDCONTROLLERLEFT_FADE = 100,
		CFI_VRHANDLEFT_POSITION = 111,
		CFI_VRHANDLEFT_ROTATION = 112,
		CFI_VRHANDLEFT_BONE_ROTATIONS = 120, 

		CFI_VRHANDCONTROLLERRIGHT_FADE = 200,
		CFI_VRHANDRIGHT_POSITION = 211,
		CFI_VRHANDRIGHT_ROTATION = 212,
		CFI_VRHANDRIGHT_BONE_ROTATIONS = 220, 
				
		CFI_VRHANDRIGHT_PADDLEBODY = 89, 
		
		CFI_SKELETON_BONE_ROTATIONS = 1400,
		CFI_SKELETON_BONE_POSITIONS = 1500,
		
	 }
