class_name NCONSTANTS2

enum {  CFI_TIMESTAMP 		= -1, 
		CFI_TIMESTAMPPREV 	= -2,
		
		CFI_PLAYER_NODENAME	= -3,
		CFI_TIMESTAMP_F0 	= -4,
		CFI_TIMESTAMP_RECIEVED = -5, 
		CFI_ZERO = 0,
		
		CFI_VRORIGIN_POSITION = 50,
		CFI_VRORIGIN_ROTATION = 51,
		CFI_VRHEAD_POSITION = 60,
		CFI_VRHEAD_ROTATION = 61,
		CFI_VRHANDLEFT_POSITION = 70,
		CFI_VRHANDLEFT_ROTATION = 71,
		CFI_VRHANDRIGHT_POSITION = 80,
		CFI_VRHANDRIGHT_ROTATION = 81,
		
		CFI_VRHANDLEFT_POSE = 72,
		CFI_VRHANDRIGHT_POSE = 82,
	 }
