class_name NCONSTANTS2

enum {  CFI_TIMESTAMP 		= -1, 
		CFI_TIMESTAMPPREV 	= -2,
		
		CFI_PLAYER_NODENAME	= -3,
		CFI_TIMESTAMP_F0 	= -4,
		CFI_TIMESTAMP_RECIEVED = -5, 
		CFI_ZERO = 0,
		
		CFI_VRORIGIN_POSITION = 50,
		CFI_VRORIGIN_ROTATION = 51,
		CFI_VRHEAD_POSITION = 60,
		CFI_VRHEAD_ROTATION = 61,
		
		CFI_VRCONTROLLERLEFT_VISIBLE = 70,
		CFI_VRCONTROLLERLEFT_POSITION = 71,
		CFI_VRCONTROLLERLEFT_ROTATION = 72,
		CFI_VRCONTROLLERRIGHT_VISIBLE = 80,
		CFI_VRCONTROLLERRIGHT_POSITION = 81,
		CFI_VRCONTROLLERRIGHT_ROTATION = 82,

		CFI_VRHANDLEFT_VISIBLE = 110,
		CFI_VRHANDLEFT_POSITION = 111,
		CFI_VRHANDLEFT_ROTATION = 112,
		CFI_VRHANDRIGHT_VISIBLE = 130,
		CFI_VRHANDRIGHT_POSITION = 131,
		CFI_VRHANDRIGHT_ROTATION = 132,
		
		CFI_VRHANDLEFT_POSE = 72,
		CFI_VRHANDRIGHT_POSE = 82,
		
		CFI_VRHANDRIGHT_PADDLEBODY = 89,		
	 }
